steps:
  # Display gcloud version, this step seems incorrect as per its current usage. Assuming it's for debug, adjust if needed.
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['--version']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/users-service:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/users-service:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'users-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/users-service:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--verbosity=debug'
    - '--allow-unauthenticated'
    - '--port'  # Specify the port here
    - '5000'
    env:
    - 'APP_PORT=5000'
images:
  - 'gcr.io/$PROJECT_ID/users-service:$COMMIT_SHA'