name: DEPLOY

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Setup Google Cloud SDK with a specific version
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0 # Use the latest version
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Trigger Cloud Build without unnecessary custom substitutions
      - name: Trigger Cloud Build
        run: gcloud builds submit --no-source --config=cloudbuild.yaml
