name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install

      - name: Code quality
        run: yarn run format

      - name: Build app
        run: yarn run build

      - name: Run tests
        run: yarn run test --passWithNoTests
